Shared state composable ViewStore example
Lickability/ViewStore pull request #13
Opened 2023-04-05 15:09 UTC by Pearapps

Provides a simple demonstration of the ability to compose `Store`s.

2023-04-06 18:17 UTC, Cordavi commented on Example/Photos/Network.swift
> +        var psa: PSA? {
What is a psa?

2023-04-11 20:05 UTC, mliberatore requested changes
I think that's everything!

2023-04-11 20:05 UTC, mliberatore commented on Example/Photos/With Stores/Banner Feature/View Level/BannerUpdateViewStore.swift
> +        }
Regardless of the error refactor mentioned above, I think this could be reduced to one line.
```suggestion
        var error: MockBannerNetworkStateController.Error? {
            return bannerViewState.networkState.error
        }
```

2023-04-11 20:05 UTC, mliberatore commented on Example/Photos/With Stores/Banner Feature/View Level/BannerView.swift
> +    /// The `Banner` to display
```suggestion
/// Simple view to show a banner.
struct BannerView: View {
    
    /// The `Banner` to display.
```

2023-04-11 20:05 UTC, mliberatore commented on Example/Photos/With Stores/PhotoList.swift
> +                    .sheet(isPresented: store.makeBinding(stateKeyPath: \.showUpdateView, actionCasePath: /PhotoListViewStore.Action.showUpdateView)) {
Can we move this binding to a computed property on the view store? I'm most concerned about consistency with `makeBinding` usage across this project, though both are acceptable.

2023-04-11 20:05 UTC, mliberatore commented on Package.swift
> +        ], path: "Sources/Store")
Did this end up being necessary because of the directory structure name without project/package name change?

2023-04-11 20:12 UTC, Cordavi commented on Example/Photos/With Stores/Banner Feature/View Level/BannerUpdateViewStore.swift
> +        let bannerViewState: BannerDataStore.State
Docs

2023-04-11 20:12 UTC, Cordavi commented on Example/Photos/With Stores/Banner Feature/View Level/BannerUpdateViewStore.swift
> +    var workingTitle: Binding<String> {
Docs

2023-04-11 20:12 UTC, Cordavi commented on Example/Photos/With Stores/Banner Feature/View Level/BannerUpdateViewStore.swift
> +        .init(get: {
I think we have a makeBinding version for this. At least we do in our other project.

2023-04-13 15:55 UTC, Pearapps commented on Example/Photos/With Stores/Banner Feature/BannerDataStore.swift
> +    enum Action {
These are Part of the `Store` protocol, and I am not sure meaningful docs could be made at the top level, thoughts on that?

2023-04-13 16:01 UTC, mliberatore commented on Example/Photos/With Stores/Banner Feature/BannerDataStore.swift
> +    enum Action {
Protocol conformance declarations don't require docs (https://github.com/Lickability/swift-best-practices/blob/main/DocumentationAndComments.md), so I think you're good here. If the cases (since they're unique in this conformance) weren't documented, I‘d probably request that, but they already are in this case.

2023-04-13 16:10 UTC, Pearapps commented on Example/Photos/With Stores/Banner Feature/BannerDataStore.swift
> +    enum Action {
actually asked this here: https://lickability.slack.com/archives/C0239B5L1RN/p1681402082294839

2023-04-13 16:56 UTC, Twigz commented on Package.swift
> +        ], path: "Sources/Store")
Yup

2023-05-09 17:05 UTC, Pearapps commented
Updated a bunch of stuff here.... I _think_ we should be better now

2023-05-10 14:58 UTC, mliberatore requested changes
Code looks great. Most of these comments are tiny suggestions or simple docs-related stuff. One general piece of feedback I have is about the contents of the docs similar to the following:

```swift
/// State of the banner data store
let bannerState: BannerDataStore.State

/// Determines if the update view should be shown
let showUpdateView: Bool
```

These docs mostly reword the property name without additional context added. I know in some cases, there _really isn’t_ much that could be added to further explain what a symbol’s name already self-documents (like `Banner`’s `title` at the top of the diff), and that makes the task of adding documentation to adhere to guidelines pretty tedious. But in some cases, particularly like `showUpdateView`, I think we could be more specific, answering questions like "what is an update view"? For example: `Determines whether to show a view that allows the user to enter new text for the banner`.

2023-05-10 14:58 UTC, mliberatore commented on Example/Photos/With Stores/Banner Feature/MockBannerNetworkStateController.swift
> +        /// - Parameter Result: A result type containing a `Banner` on success or an `NSError` on failure.
```suggestion
        /// - Parameter Result: A result type containing a `Banner` on success or an `NetworkError` on failure.
```

2023-05-10 14:58 UTC, mliberatore commented on Example/Photos/With Stores/Banner Feature/View Level/BannerUpdateView.swift
> +            if success { dismiss() }
I don’t think we have a specific guideline around this, but one-lining conditional expressions is not something I see to often in our code, with the exception of simple `guard`s and `case` statements. Do you mind expanding this out to multiple lines, or otherwise can we more formally pitch one-lining?

2023-05-10 14:58 UTC, mliberatore commented on Example/Photos/With Stores/Banner Feature/View Level/BannerUpdateViewStore.swift
> +        // Returns an NSError object if there is an error in the network state when it's finished, otherwise returns nil
```suggestion
        // Returns a `NetworkError` if there is an error in the network state when it's finished, otherwise returns nil
```

2023-05-10 14:58 UTC, mliberatore commented on Example/Photos/With Stores/Banner Feature/View Level/BannerUpdateViewStore.swift
> +    /// Enum that defines possible actions that can be performed on the `BannerUpdateViewStore`
Some inconsistency with documenting `Action` at the top level here, vs. not in `BannerDataStore`. My vote would be to delete the top level doc on this line, with the justification that the type is already documented in `Store`, leaving only the `case`s with formal docs. Much like a parameterless `init`, I think the docs for `Action` would kinda always be the same for each type, swapping in the type name.

2023-05-10 14:58 UTC, mliberatore commented on Example/Photos/With Stores/PhotoListViewStore.swift
> +    /// State represents the current state of the photo list view store
Same comment that I left about top-level `Action` docs. I think this line be removed.

2023-05-10 14:58 UTC, mliberatore commented on Example/Photos/With Stores/PhotoListViewStore.swift
> +        /// Computed property to get the banner from the bannerState
```suggestion
        /// Computed property to get the `banner` from `bannerState`
```

2023-05-10 14:58 UTC, mliberatore commented on Example/Photos/With Stores/PhotoListViewStore.swift
> +    /// Computed property that creates a binding for the showsPhotoCount state
Some inconsistency in docs here. Other docs that’ve been added back-tick the symbols referenced but these docs don’t. Honestly not super important, but consistency would be nice. I‘ll stop commenting on individual ones.

2023-05-16 15:35 UTC, Pearapps commented
Did another pass on this, this morning!

2023-05-16 15:41 UTC, Pearapps commented
> Code looks great. Most of these comments are tiny suggestions or simple docs-related stuff. One general piece of feedback I have is about the contents of the docs similar to the following:
> 
> ```swift
> /// State of the banner data store
> let bannerState: BannerDataStore.State
> 
> /// Determines if the update view should be shown
> let showUpdateView: Bool
> ```
> 
> These docs mostly reword the property name without additional context added. I know in some cases, there _really isn’t_ much that could be added to further explain what a symbol’s name already self-documents (like `Banner`’s `title` at the top of the diff), and that makes the task of adding documentation to adhere to guidelines pretty tedious. But in some cases, particularly like `showUpdateView`, I think we could be more specific, answering questions like "what is an update view"? For example: `Determines whether to show a view that allows the user to enter new text for the banner`.

I went through and tried to beef up some of the docs, even if only a little. I am struggling with some of them to add additional context

2023-05-16 16:05 UTC, mliberatore approved these changes
Looks great 🙌. One tiny grammar correction, then feel free to merge it with no further review.

2023-05-16 18:16 UTC, Pearapps commented
Thank you @mliberatore ! Appreciate your reviews and patience with this!

2023-05-17 14:01 UTC, merged

2023-05-17 14:09 UTC, mliberatore commented
:tada: